data:
  train_dir: datasets/processed # training data directory
  # val_dir: data 
  batch_size: 32 # Batch size for the dataloaders
  img_size: 24 # Image size to be fed into the model
  loader_num_workers: 1 # Number of cpu cores to use for dataloaders

train:
  num_epochs: 50 # number of training epochs
  learning_rate: 0.001 # model learning rate