data:
  train_dir: datasets/processed # training data directory
  # val_dir: data 
  batch_size: 200 # Batch size for the dataloaders
  img_size: 224 # Image size to be fed into the model
  num_workers: 1 # Number of cpu cores to use for dataloaders